from .main_routes import main_routes
from .auth_routes import auth_routes
from .citas_routes import citas_routes
from .usuario_routes import usuario_routes
from .pacientes_routes import paciente_routes
from .inventario_routes import inventario_routes
from .personal_routes import personal_routes
from .procedimientos_routes import procedimientos_routes_routes
from .consultorios_routes import consultorios_routes
from .servicios_routes import servicios_routes
from .finanzas_routes import finanzas_routes
from .reportes_routes import reportes_routes